### ISSUE TITLE
API test todo's

### ISSUE THREAD

**Issue by jmeas** [jmeas/moolah#158]
- [ ] Use Babel plugin rewire to test internals + in isolation (#140)
- [ ] Test root endpoint 
- [ ] 1 endpoint per file (#121)
- [ ] more unit tests
- [ ] test creation throwing error (#141)
- [ ] test for passing an invalid ID (like /transactions/asdf`)
