### ISSUE TITLE
Mock to-do

### ISSUE THREAD

**Issue by jmeas** [jmeas/moolah#298]
This is the full list of things I still need to create mocks for:
#### Alerts
- [x] Success (no detail)
- [x] Success (with detail)
- [x] Info (no detail)
- [x] Info (with detail)
- [x] Warning (no detail)
- [x] Warning (with detail)
- [x] Danger (no detail)
- [x] Danger (with detail)
#### Modal
- [x] Modal with header and buttons
- [x] Modal with loading buttons
- [x] Modal with simple form
#### Alerts + Modals
- [x] Alerts and modals displaying at once
- [x] Alerts overlapping modals
#### Profile
- [x] Initial load failed
- [x] Initial load success
##### Photo
- [x] No profile photo
- [x] Change photo dialog
- [x] Change photo uploading
- [x] Change photo success
- [x] Change photo error
- [x] Invalid input (and reasons. i.e.; too large, wrong format)
##### Name/email
- [x] Read-only mode
- [x] Edit dialog
- [ ] Edit success/fail
- [x] Invalid input (too long, nonexistent, etc.)
##### Logins
- [ ] One login left
- [ ] Removing login in progress
- [ ] Remove login fail
#### About
- [x] mobile page
- [x] desktop page
#### Privacy policy
- [x] mobile page
- [ ] desktop page
#### Transactions
- [x] Empty month
- [x] When "next month" link is disabled
- [ ] Loading initial transactions
- [ ] Loading more transactions, or paginating? (the # of transactions initially shown at once will be restricted)
- [ ] Modal for add new transaction
- [ ] Modal for add new recurring transaction
- [ ] Modal for edit transaction
- [ ] Modal for edit recurring transaction
- [ ] Selecting category for transaction
- [ ] Delete transaction success/fail
- [ ] Delete transaction loading
- [ ] Edit transaction success/fail
- [ ] Create transaction success/fail
- [ ] Create/edit validation fail
- [ ] Load initial transaction fail
- [ ] Load fail fetching more / paginating
- [ ] Datepicker design
- [ ] All of the above...for desktop
#### Categories
- [ ] emoji picker (mobile and desktop)
- [ ] desktop views
- [ ] new modals
- [ ] validation fail
- [ ] load error
#### Analytics
- [ ] basic sketches are needed first
#### Landing page
- [x] what you see when not logged in
#### Dashboard
- [ ] desktop view

**Comment by jmeas** [comment]
@jasonLaster had some good ideas for updating the transactions page. I took some notes down for that, and I should make sure those land in any new mocks that I do.

**Comment by jmeas** [comment]
Gonna close this. I've got enough done that I'll be able to code up v1 of the app.
